"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING

from seaborn._marks.base import (
    MappableBool,
    MappableColor,
    MappableFloat,
    MappableString,
    MappableStyle,
    Mark,
    document_properties,
)

if TYPE_CHECKING: ...

class DotBase(Mark): ...

@document_properties
@dataclass
class Dot(DotBase):
    """
    A mark suitable for dot plots or less-dense scatterplots.

    See also
    --------
    Dots : A dot mark defined by strokes to better handle overplotting.

    Examples
    --------
    .. include:: ../docstrings/objects.Dot.rst

    """

    marker: MappableString = ...
    pointsize: MappableFloat = ...
    stroke: MappableFloat = ...
    color: MappableColor = ...
    alpha: MappableFloat = ...
    fill: MappableBool = ...
    edgecolor: MappableColor = ...
    edgealpha: MappableFloat = ...
    edgewidth: MappableFloat = ...
    edgestyle: MappableStyle = ...

@document_properties
@dataclass
class Dots(DotBase):
    """
    A dot mark defined by strokes to better handle overplotting.

    See also
    --------
    Dot : A mark suitable for dot plots or less-dense scatterplots.

    Examples
    --------
    .. include:: ../docstrings/objects.Dots.rst

    """

    marker: MappableString = ...
    pointsize: MappableFloat = ...
    stroke: MappableFloat = ...
    color: MappableColor = ...
    alpha: MappableFloat = ...
    fill: MappableBool = ...
    fillcolor: MappableColor = ...
    fillalpha: MappableFloat = ...
