"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING, ClassVar

from pandas import DataFrame
from seaborn._core.groupby import GroupBy
from seaborn._core.scales import Scale

"""Base module for statistical transformations."""
if TYPE_CHECKING:
    ...
@dataclass
class Stat:
    """Base class for objects that apply statistical transformations."""
    group_by_orient: ClassVar[bool] = ...
    def __call__(self, data: DataFrame, groupby: GroupBy, orient: str, scales: dict[str, Scale]) -> DataFrame:
        """Apply statistical transform to data subgroups and return combined result."""
        ...
