"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass

from seaborn._stats.base import Stat

@dataclass
class PolyFit(Stat):
    """
    Fit a polynomial of the given order and resample data onto predicted curve.
    """

    order: int = ...
    gridsize: int = ...
    def __call__(self, data, groupby, orient, scales):  # -> DataFrame:
        ...

@dataclass
class OLSFit(Stat): ...
