---
title: "Table S71"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '~/Repo/Schief856_G002/data/dropbox/Stats.codebase'
```


\clearpage


```{r comp}
dat = read.csv(file.path(STATS, 'fig4masking_pvals.csv'))

dat = dat %>%
  mutate(p.value = VISCfunctions::pretty_pvalues(p.value, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow"),
         fdr  = VISCfunctions::pretty_pvalues(fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow"))

kbl(dat %>% select(comp, SampleSizes, summary, p.value, fdr),
    format = "latex",
    escape = FALSE,
    longtable = FALSE,
    booktabs = TRUE,
    linesep = '',
    row.names = FALSE,
    col.names = c('Comparison', 'Sample Sizes','Summary','P Value', 'FDR'),
    caption="Table S71. Comparison of Group 2 week 8 vs. week 16 responses and Group 3 week 16 vs. week 24 responses
    using a Wilcoxon signed-rank test and comparison of Group 2 fold-change of week 16 responses over week 8 responses
    to Group 3 week 24 responses over week 16 responses using a Wilcoxon rank-sum test. Note, fold-change analysis is conditional on a defined fold-change (i.e., denominator greater than zero). Summary gives group values for the median and range. P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  column_spec(1, border_right = TRUE) %>%
  kable_styling(
    font_size = 6.5,
    latex_options = c("hold_position", "repeat_header")
    ) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE, escape=TRUE)


```
