---
title: "Table S61"
date: "`r Sys.Date()`"
geometry: "left=0.5in, right=0.5in, top=0.5in, bottom=0.25in"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '/Users/tmsincomb/Dropbox/repos/G002-and-G003/src/VISC_codebase/data/Stats.codebase'
```


\clearpage

```{r figure5}

dat = read.csv(file.path(STATS, 'fig5_by_method_pvals.csv'))
dat = subset(dat, method=='median unbiased')
dat$p.value = pretty_pvalues(dat$p.value, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow")
dat$fdr = pretty_pvalues(dat$fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")
dat$weeks[which(dat$weeks[-1] == dat$weeks[-length(dat$weeks)]) + 1] ='\\hfill'
dat$comp = gsub('->', '$\\\\rightarrow$', dat$comp)

kbl(dat %>% select(weeks, comp, SampleSizes, Median_Min_Max, p.value, fdr),
    format = "latex",
    escape = FALSE,
    longtable = TRUE,
    booktabs = TRUE,
    row.names = FALSE,
    col.names = c('Week', 'Group', 'Sample Sizes', 'Median (Range)', 'P-value', 'FDR'),
    caption="Table S61.  Testing between independent groups was done using the Wilcoxon rank-sum test for continuous outcomes. Testing across time was done using the Wilcoxon signed-rank test for continuous outcomes and paired data except for the eOD->core at wk16 vs. eOD->eOD->core at wk24 comparison which uses the Wilcoxon rank-sum test for independent continous outcomes P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  kable_styling(font_size = 8) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE)
```
