---
title: "Table S66"
date: "`r Sys.Date()`"
geometry: "left=0.5in, right=0.5in, top=0.5in, bottom=0.25in"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '~/Repo/Schief856_G002/data/dropbox/Stats'
```

\clearpage


```{r neut_ic50_v2}
dat = read.csv(file.path(STATS, 'Neut_pvalues.csv'))
dat = subset(dat, outcome=='ic50_v2')
dat$p.value = pretty_pvalues(dat$p.value, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow")
dat$fdr = pretty_pvalues(dat$fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")
dat$comp = gsub('->', '$\\\\rightarrow$', dat$comp)
dat$est = sprintf('%0.4f', dat$est)
dat$lci = sprintf('%0.4f', dat$lci)
dat$uci = sprintf('%0.4f', dat$uci)

kbl(dat %>% dplyr::select(week, comp, est, lci, uci, p.value, fdr) %>% ungroup(),
    align = 'lllrrrrr',
    format = "latex",
    escape = FALSE,
    longtable = TRUE,
    booktabs = TRUE,
    row.names = FALSE,
    linesep = '',
    col.names = c('Week', 'Group', 'Difference', 'LCI', 'UCI', 'P-value', 'FDR'),
    caption="Table S66. Neutralization of N276-lacking pseudoviruses. Testing between groups was done using GEE. Difference is the geometric mean IC50 of Group 2 versus Group 1 with the lower (LCI) and upper 95\\% confidence interval (UCI).  IC50 values less than the limit of detection (10 or 50 $\\mu$g/mL) are imputed as the limit of detection for analysis.
    P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  kable_styling(font_size = 7.5)
```
