---
title: "Table S78"
date: "`r Sys.Date()`"
geometry: "left=0.5in, right=0.5in, top=0.5in, bottom=0.25in"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '~/Repo/Schief856_G002/data/dropbox/Stats.codebase'
```

\clearpage

```{r neut_g1}
dat = read.csv(file.path(STATS, 'Fig8A_pvalues.csv'))
dat$outcome=gsub('_', '-', dat$outcome)
dat$p.value = pretty_pvalues(dat$p.value, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow")
dat$fdr = pretty_pvalues(dat$fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")
dat$comp = gsub('->', '$\\\\rightarrow$', dat$comp)
dat$wk16 = sprintf('%0.4f', dat$wk16*10^6)
dat$wk24 = sprintf('%0.4f', dat$wk24*10^6)
dat$est = sprintf('%0.4f', dat$est)
dat$lci = sprintf('%0.4f', dat$lci)
dat$uci = sprintf('%0.4f', dat$uci)

kbl(dat %>% dplyr::select(outcome, wk16, wk24, est, lci, uci, p.value, fdr) %>% ungroup(),
    align = 'lrrrrrrrr',
    format = "latex",
    escape = FALSE,
    longtable = TRUE,
    booktabs = TRUE,
    row.names = FALSE,
    linesep = '',
    col.names = c('Immunogen', 'GM16', 'GM24', 'Geometric Mean Ratio', 'LCI', 'UCI', 'P-value', 'FDR'),
    caption="Table S78. Testing between groups was done using GEE. The estimated geometric mean in $\\mu$M are for Week 16 and Week 24 are shown in the GM16 and GM24 columns.  Geometric Mean Ratio the ratio of the Gemetric Mean estimated at Week 24 verus Week 16 with the lower (LCI) and upper 95\\% confidence interval (UCI). Testing was done using GEE conditional on K$_{\\textbf{D}} < 50\\mu$M. P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  kable_styling(font_size = 7.5)
```
