---
title: "Table S55"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '~/Repo/Schief856_G002/data/dropbox/Stats.codebase'
```


\clearpage


```{r post_v_post_fig3_nearest}
dat = read.csv(file.path(STATS, 'G00X_mag_postbaseline_v_postbaseline_fig3ABE_by_method.csv')) %>%
  filter(method=='nearest') %>%
  group_by(panel) %>%
  mutate(fdr = p.adjust(MagnitudeTest, 'fdr')) %>%
  mutate(pval = VISCfunctions::pretty_pvalues(MagnitudeTest, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow"),
         fdr  = VISCfunctions::pretty_pvalues(fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")) %>%
  ungroup() %>%
  arrange(panel, trial, order) %>%
  select(panel, trial, Comparison, SampleSizes, Median_Min_Max, pval, fdr)
dat$trial[which(dat$trial[-1] == dat$trial[-length(dat$trial)]) + 1] ='\\hfill'

kbl(dat %>% dplyr::select(-panel),
    format = "latex",
    escape = FALSE,
    longtable = FALSE,
    booktabs = TRUE,
    linesep = '',
    row.names = FALSE,
    col.names = c('Trial','Comparison','Number of Pairs', 'Median (Range)', 'P Value', 'FDR'),
    caption="Table S55. (A) Percent mutation of V$_{\\text{H}}$ gene (aa), (B) Percent mutation of V$_{\\text{K/L}}$ gene (aa),
    and (E) 90$^{\\text{th}}$ percentile of number of key VRC01-class HC residues
    magnitude testing between non-baseline time points by trial. Testing was
    done using Wilcoxon signed-rank test for paired data; P values less than 0.05
    and Q values less than 0.2 are highlighted.") %>%
  column_spec(1, border_right = TRUE) %>%
  kable_styling(
    font_size = 8,
    latex_options = c("hold_position", "repeat_header")
    ) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE, escape=TRUE)

```
