---
title: "Tables S45, S46, and S47"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(knitr.kable.NA = '')

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '~/Repo/Schief856_G002/data/dropbox/Stats.codebase'
```

\clearpage


```{r response_rate_table}
dat = read.csv(file.path(STATS, 'G00X_response_call_panelsAB.csv')) %>%
  filter(weeks > 0) %>%
  pivot_wider(id_cols = c(panel, weeks), names_from = trial, values_from = sum_info) %>%
  arrange(panel, weeks)

kbl(dat %>% dplyr::select(-panel),
    format = "latex",
    escape = FALSE,
    longtable = FALSE,
    booktabs = TRUE,
    linesep = '',
    row.names = FALSE,
    col.names = c('Week', 'G001', 'G002', 'G003'),
    caption="Table S45. Number of (A) GT8++ (regardless of KO binding status) and (B) epitope-specific(KO-GT8++)
    responders by trial and time point, with accompanying Wilson score confidence intervals.") %>%
  column_spec(1, border_right = TRUE) %>%
  column_spec(2:4, width = '4.6cm') %>%
  kable_styling(
    font_size = 7.5,
    latex_options = c("hold_position", "repeat_header")
    ) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE, escape=TRUE)
```

\clearpage


```{r baseline_v_post_mag}
dat = read.csv(file.path(STATS, 'G00X_mag_baseline_v_post.csv')) %>%
  mutate( comp_wk = as.numeric(str_remove(Comparison, 'Wk-5 vs. Wk')) ) %>%
  group_by(panel) %>%
  mutate(fdr = p.adjust(MagnitudeTest, 'fdr')) %>%
  mutate(pval = VISCfunctions::pretty_pvalues(MagnitudeTest, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow"),
         fdr  = VISCfunctions::pretty_pvalues(fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")) %>%
  ungroup() %>%
  arrange(panel, trial, comp_wk) %>%
  select(panel, trial, Comparison, SampleSizes, Median_Min_Max, pval, fdr)
dat$trial[which(dat$trial[-1] == dat$trial[-length(dat$trial)]) + 1] ='\\hfill'

kbl(dat %>% dplyr::select(-panel),
    format = "latex",
    escape = FALSE,
    longtable = FALSE,
    booktabs = TRUE,
    linesep = '',
    row.names = FALSE,
    col.names = c('Trial','Comparison','Number of Pairs', 'Median (Range)', 'P Value', 'FDR'),
    caption="Table S46. Percent of (A) IgG+ B cells that are GT8++ (regardless of KO binding status), (B)
    IgG+ B cells that are epitope-specific (KO-GT8++), (C) GT8++IgG+ B cells that are KO-
    and (E) IgG+ B cells detected as VRC01-class magnitude testing
    between baseline (Week -5) and post-baseline time points by trial. Testing was
    done using Wilcoxon signed-rank test for paired data.
    P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  column_spec(1, border_right = TRUE) %>%
  kable_styling(
    font_size = 8,
    latex_options = c("hold_position", "repeat_header")
    ) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE, escape=TRUE)

```


\clearpage

```{r post_v_post_fig2}
dat = read.csv(file.path(STATS, 'G00X_mag_postbaseline_v_postbaseline.csv'))
dat_FG = read.csv(file.path(STATS, 'G00X_mag_postbaseline_v_postbaseline_panelFG.csv'))
# %>%
#   mutate(panel = 'F') # unfortunately R reads in the panel value as FALSE instead of F

dat = rbind(dat, dat_FG) %>%
  group_by(panel) %>%
  mutate(fdr = p.adjust(MagnitudeTest, 'fdr')) %>%
  mutate(pval = VISCfunctions::pretty_pvalues(MagnitudeTest, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow"),
         fdr  = VISCfunctions::pretty_pvalues(fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")) %>%
  ungroup() %>%
  arrange(panel, trial, order) %>%
  select(panel, trial, Comparison, SampleSizes, Median_Min_Max, pval, fdr)
dat$trial[which(dat$trial[-1] == dat$trial[-length(dat$trial)]) + 1] ='\\hfill'

kbl(dat %>% dplyr::select(-panel),
    format = "latex",
    escape = FALSE,
    longtable = FALSE,
    booktabs = TRUE,
    linesep = '',
    row.names = FALSE,
    col.names = c('Trial','Comparison','Number of Pairs', 'Median (Range)', 'P Value', 'FDR'),
    caption="Table S47. Percent of (A) IgG+ B cells that are GT8++ (regardless of KO binding status), (B)
    IgG+ B cells that are epitope-specific (KO-GT8++), (C) GT8++IgG+ B cells that are KO-,
    (E) IgG+ B cells detected as VRC01-class, (F) CD4bs-specific IgG+ B cells detected as VRC01-class, and
    (G) GT8-specific IgG+ B cells detected as VRC01-class magnitude testing between non-baseline
    time points by trial. Testing was done using Wilcoxon signed-rank test for paired data;
    P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  column_spec(1, border_right = TRUE) %>%
  kable_styling(
    font_size = 8,
    latex_options = c("hold_position", "repeat_header")
    ) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE, escape=TRUE)

```
