---
title: "Table S57"
date: "`r Sys.Date()`"
geometry: "left=0.5in, right=0.5in, top=0.5in, bottom=0.25in"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}
\clearpage

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '~/Repo/Schief856_G002/data/dropbox/Stats'
```


\clearpage

```{r figure4}
dat = read.csv(file.path(STATS, 'fig4_pvals.csv'))
dat$p.value = pretty_pvalues(dat$p.value, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow")
dat$fdr = pretty_pvalues(dat$fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")
dat$weeks[which(dat$weeks[-1] == dat$weeks[-length(dat$weeks)]) + 1] ='\\hfill'
dat$comp = gsub('->', '$\\\\rightarrow$', dat$comp)

kbl(dat %>% dplyr::select(weeks, comp, SampleSizes, summary, p.value, fdr) %>% ungroup(),
    format = "latex",
    escape = FALSE,
    longtable = TRUE,
    booktabs = TRUE,
    row.names = FALSE,
    col.names = c('Week', 'Group', 'Sample Sizes', 'Summary', 'P-value', 'FDR'),
    caption="Table S57.  Testing between independent groups was done using the Wilcoxon rank-sum test for continuous outcomes (all panels except E) and Barnard’s exact test for the binary outcome in panel E. Comparisons across time within a single regimen use a Wilcoxon signed-rank test (all panels except E) and McNemar's test (panel E; the P-value is NA for comparisons at weeks 16 vs. 24 when the responses are perfectly concordant). Summary gives group values for the median and range for continuous outcomes and counts of positive responses out of the total with response rate and 95\\% Wilson confidence interval for the binary outcome of panel E. P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  kable_styling(font_size = 5.5) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE, escape=TRUE)
```
