---
title: "Table S67"
date: "`r Sys.Date()`"
geometry: "left=0.5in, right=0.5in, top=0.5in, bottom=0.25in"
output: pdf_document
header-includes:
    - \usepackage{caption}
---

\captionsetup[table]{labelformat=empty}


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(VISCfunctions)
library(kableExtra)

# csv files are saved here
STATS = '~/Repo/Schief856_G002/data/dropbox/Stats.codebase'
```


\clearpage

```{r figure}
dat = read.csv(file.path(STATS, 'fig7_pvals.csv'))
dat = subset(dat, !is.na(p.value))
dat$p.value = pretty_pvalues(dat$p.value, digits = 4, sig_alpha=0.05, missing_char='NA', background = "yellow")
dat$fdr = pretty_pvalues(dat$fdr, digits = 4, sig_alpha=0.2, missing_char='NA', background = "yellow")
dat$weeks[which(dat$weeks[-1] == dat$weeks[-length(dat$weeks)] & dat$panel[-1] == dat$panel[-length(dat$panel)]) + 1] ='\\hfill'
dat$comp = gsub('->', '$\\\\rightarrow$', dat$comp)

kbl(dat %>% dplyr::select(weeks, comp, SampleSizes, summary, p.value, fdr) %>% ungroup(),
    format = "latex",
    escape = FALSE,
    longtable = TRUE,
    booktabs = TRUE,
    row.names = FALSE,
    col.names = c('Week', 'Comparison', 'Sample Sizes', 'Summary', 'P-value', 'FDR'),
    caption="Table S67. Testing between groups was done using the Wilcoxon rank-sum test for continuous outcomes and Barnard’s exact test for the binary outcome. Summary gives group values for the median and range for continuous outcomes and counts of positive responses out of the total with response rate and 95\\% Wilson confidence interval for the binary outcome of panel E. P values less than 0.05 and Q values less than 0.2 are highlighted.") %>%
  kable_styling(font_size = 6.5) %>%
  pack_rows(index=table(dat$panel), hline_before = TRUE, hline_after = TRUE, escape=TRUE)
```
