---
title: "Statistical Methods"
output: github_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r pool-groups-and-summarize, warning=T}

bcell_adata_long_pooled <- bcell_adata_long %>% 
  group_by(Weeks, `Probe Set`, `Previous Doses`) %>%
  ungroup() %>% 
  mutate(Pooled_Treatment = case_when(is.na(`Previous Doses`) ~ 'Baseline',  
                                      .default = str_replace_all(`Previous Doses`, ',', ' →')),
         Group_Treatment = paste0('Group ', Group, ': ', Treatment),
         Weeks_Post_Core = case_when((`Probe Set` == 'Core-g28v2') & (Group == 4) ~ Weeks,
                                     (`Probe Set` == 'Core-g28v2') & (Group == 2) ~ Weeks - 8,
                                     (`Probe Set` == 'Core-g28v2') & (Group == 3) ~ Weeks - 16,
                                     .default = NA))

# # add in the Core sort Groups 1 and 3 pooled at Week 16
# bcell_adata_long_pooled <- bind_rows(
#   bcell_adata_long_pooled,
#   bcell_adata_long_pooled %>% 
#     filter(`Probe Set` == 'Core-g28v2', Weeks == 16, Group %in% c(1, 3)) %>%
#     mutate(Pooled_Treatment = 'eOD → eOD (Groups 1 and 3)')
# )

# # add in the "any number of eOD-GT8 doses" category
# bcell_adata_long_pooled <- bind_rows(
#   bcell_adata_long_pooled,
#   bcell_adata_long_pooled %>%
#     filter(!str_detect(`Previous Doses`, 'Core')) %>%
#     mutate(Pooled_Treatment = 'eOD (1+ dose) and no Core')
# )

wilson_ci_allowing_missing_responses <- function(x) {
  if (any(!is.na(x))) {
    wilson_ci(x)
  } else {
    data.frame(mean = NA, lower = NA, upper = NA)
  }
}
  
# summarizing the critical features of the pooled data
bcell_adata_long_summary <- bcell_adata_long_pooled %>%
  filter(!is.na(Magnitude)) %>%
  mutate(pos_magnitude = ifelse(`Response Call` == T, Magnitude, NA)) %>%
  group_by(Pooled_Treatment, Weeks, Week_Label, `Sample Type`, `Probe Set`, is_baseline, Endpoint) %>%
  summarize(wilson_ci_allowing_missing_responses(`Response Call`),
            magnitude_median = median(Magnitude, na.rm=T),
            pos_magnitude_median = median(pos_magnitude, na.rm=T),
            magnitude_min = min(Magnitude, na.rm=T),
            pos_magnitude_min = ifelse(any(`Response Call`==T), min(pos_magnitude, na.rm=T), NA), 
            magnitude_max = max(Magnitude, na.rm=T),
            pos_magnitude_max = ifelse(any(`Response Call`==T), max(pos_magnitude, na.rm=T), NA),
            .groups='drop') %>%
  mutate(mean = ifelse(is_baseline, NA, mean),
         lower = ifelse(is_baseline, NA, lower),
         upper = ifelse(is_baseline, NA, upper)) %>%
  rename(mean_response_rate = mean,
         lower_response_rate = lower,
         upper_response_rate = upper)
```

```{r run-tests-response-rates-across-groups}

pooled_rr_df <- bind_rows(
  
  bcell_adata_long_pooled %>% filter(!is.na(`Response Call`)),
  
  bcell_adata_long_pooled %>% 
    filter(!is.na(`Response Call`), !is.na(Weeks_Post_Core)) %>% 
    mutate(Week_Label = ifelse(Weeks_Post_Core == 0, 'prior to Core dose', paste(Weeks_Post_Core, 'weeks post-Core')))
           
) %>%
  group_by(Week_Label, `Sample Type`, `Probe Set`, Endpoint) %>%
  mutate(n_pooled_group_rx = n_distinct(Pooled_Treatment)) 

if (any(pooled_rr_df$n_pooled_group_rx > 1)) {
  rr_test_results_across_groups <- pooled_rr_df %>% 
    filter(n_pooled_group_rx > 1) %>%
    group_modify(
      ~pairwise_test_bin(
        x = .$`Response Call`, group = .$Pooled_Treatment, method = 'barnard', 
        alternative = 'two.sided', num_needed_for_test = 3, digits = 1,
        latex_output = TRUE, verbose = FALSE
      )
    ) %>%  
    ungroup() %>% 
    mutate(
      ResponseTest = pretty_pvalues(
        ResponseTest, output_type = output_type, sig_alpha = .05, 
        background = 'yellow',
        bold = if_else(pandoc_markup , TRUE, FALSE),
        italic = if_else(pandoc_markup , TRUE, FALSE),
        digits = 3
      ),
      Week_Label = factor(Week_Label, levels = c('Baseline', 'Week 4', 'Week 8', 'Week 16', 'Week 24',
                                                 'prior to Core dose', '8 weeks post-Core'))
    )
} else {
  stop('No groups to comapre response rates between')
}
```

```{r run-tests-response-rates-across-time}

week_comparison_levels <- c('-5 vs. 4', '-5 vs. 8', '-5 vs. 16', '-5 vs. 24', 
                            '4 vs. 8', '4 vs. 16', '4 vs. 24',
                            '8 vs. 16', '8 vs. 24',
                            '16 vs. 24')

rr_test_results_across_time <- bcell_adata_long_pooled %>% 
  mutate(Pooled_Treatment = ifelse(`Probe Set` == 'eOD-GT8', 'Any eOD', Pooled_Treatment)) %>%
  filter(!is.na(`Response Call`)) %>%
  group_by(`Sample Type`, `Probe Set`, Endpoint, Pooled_Treatment) %>% 
  mutate(n_time_points = n_distinct(Weeks)) %>% filter(n_time_points > 1) %>%
  group_modify(
      ~pairwise_test_bin(
        x = .$`Response Call`, group = .$Weeks, id = .$PTID,
        method = 'mcnemar', 
        alternative = 'two.sided', num_needed_for_test = 3, digits = 1,
        latex_output = TRUE, verbose = FALSE
        )
    ) %>%  
  ungroup() %>% 
  mutate(
    ResponseTest = pretty_pvalues(
      ResponseTest, output_type = output_type, sig_alpha = .05, 
      background = 'yellow',
      bold = if_else(pandoc_markup , TRUE, FALSE),
      italic = if_else(pandoc_markup , TRUE, FALSE),
      digits = 3
      ),
    Comparison = factor(Comparison, levels = week_comparison_levels)
    )
```

```{r run-tests-response-magnitude-across-groups}

magnitude_test_results_across_groups <- bind_rows(
  
  bcell_adata_long_pooled %>% filter(!is.na(Magnitude)),
  
  bcell_adata_long_pooled %>% 
    filter(!is.na(Magnitude), !is.na(Weeks_Post_Core)) %>% 
    mutate(Week_Label = ifelse(Weeks_Post_Core == 0, 'prior to Core dose', paste(Weeks_Post_Core, 'weeks post-Core')))
           
) %>%
  group_by(Week_Label, `Sample Type`, `Probe Set`, Endpoint) %>%
  mutate(n_rx = n_distinct(Pooled_Treatment)) %>% filter(n_rx > 1) %>%
  group_modify(
    ~pairwise_test_cont(
      x = .$Magnitude, group = .$Pooled_Treatment, method = 'wilcox', paired = FALSE, 
      alternative = 'two.sided', num_needed_for_test = 3, digits = 3, 
      verbose = FALSE
    ) %>% as.data.frame
  ) %>%  
  ungroup() %>% 
  mutate(
    MagnitudeTest = pretty_pvalues(
      MagnitudeTest, output_type = output_type, sig_alpha = .05,
      background = 'yellow',
      bold = if_else(pandoc_markup , TRUE, FALSE),
      italic = if_else(pandoc_markup , TRUE, FALSE),
      digits = 3
    )
  ) %>% 
  rename("Median (Range)" = Median_Min_Max, 'Mean (SD)' = Mean_SD) %>%
  mutate(Week_Label = factor(Week_Label, levels = c('Baseline', 'Week 4', 'Week 8', 'Week 16', 'Week 24',
                                                    'prior to Core dose', '8 weeks post-Core')))
```

```{r run-tests-response-magnitude-across-time}

magnitude_test_results_across_time <- bcell_adata_long_pooled %>% 
  mutate(Pooled_Treatment = ifelse(`Probe Set` == 'eOD-GT8', 'Any eOD', Pooled_Treatment)) %>%
  filter(!is.na(Magnitude)) %>%
  group_by(`Sample Type`, `Probe Set`, Endpoint, Pooled_Treatment) %>%
  mutate(n_time_points = n_distinct(Weeks)) %>% filter(n_time_points > 1) %>%
  group_modify(
    ~pairwise_test_cont(
      x = .$Magnitude, group = .$Weeks, id = .$PTID,
      method = 'wilcox', paired = TRUE, 
      alternative = 'two.sided', num_needed_for_test = 3, digits = 3, 
      verbose = FALSE
    ) %>% as.data.frame
  ) %>% 
  ungroup() %>% 
  mutate(
    MagnitudeTest = pretty_pvalues(
      MagnitudeTest, output_type = output_type, sig_alpha = .05,
      background = 'yellow',
      bold = if_else(pandoc_markup , TRUE, FALSE),
      italic = if_else(pandoc_markup , TRUE, FALSE),
      digits = 3
    ),
    Post_Visit = Comparison %>% 
      str_sub(start = str_locate(Comparison, 'vs. ')[,'end'] + 1),
    Comparison = factor(Comparison, levels = week_comparison_levels)
  )
```
