"""
This type stub file was generated by pyright.
"""

from collections.abc import Generator
from typing import TYPE_CHECKING

from matplotlib.axes import Axes
from matplotlib.figure import Figure, SubFigure
from seaborn._core.plot import FacetSpec, PairSpec

if TYPE_CHECKING:
    ...
class Subplots:
    """
    Interface for creating and using matplotlib subplots based on seaborn parameters.

    Parameters
    ----------
    subplot_spec : dict
        Keyword args for :meth:`matplotlib.figure.Figure.subplots`.
    facet_spec : dict
        Parameters that control subplot faceting.
    pair_spec : dict
        Parameters that control subplot pairing.
    data : PlotData
        Data used to define figure setup.

    """
    def __init__(self, subplot_spec: dict, facet_spec: FacetSpec, pair_spec: PairSpec) -> None:
        ...

    def init_figure(self, pair_spec: PairSpec, pyplot: bool = ..., figure_kws: dict | None = ..., target: Axes | Figure | SubFigure = ...) -> Figure:
        """Initialize matplotlib objects and add seaborn-relevant metadata."""
        ...

    def __iter__(self) -> Generator[dict, None, None]:
        """Yield each subplot dictionary with Axes object and metadata."""
        ...

    def __len__(self) -> int:
        """Return the number of subplots in this figure."""
        ...
