"""
This type stub file was generated by pyright.
"""

from collections.abc import Hashable, Iterable
from datetime import date, datetime, timedelta
from typing import Any, Dict, List, Mapping, Optional, Tuple, Union

from matplotlib.colors import Colormap, Normalize
from numpy import ndarray
from pandas import DataFrame, Index, Series, Timedelta, Timestamp

ColumnName = Union[str, bytes, date, datetime, timedelta, bool, complex, Timestamp, Timedelta]
Vector = Union[Series, Index, ndarray]
VariableSpec = Union[ColumnName, Vector, None]
VariableSpecList = Union[List[VariableSpec], Index, None]
DataSource = Union[DataFrame, Mapping[Hashable, Vector], None]
OrderSpec = Union[Iterable, None]
NormSpec = Union[Tuple[Optional[float], Optional[float]], Normalize, None]
PaletteSpec = Union[str, list, dict, Colormap, None]
DiscreteValueSpec = Union[dict, list, None]
ContinuousValueSpec = Union[
    Tuple[float, float],
    List[float],
    Dict[Any, float],
    None,
]

class Default:
    def __repr__(self):  # -> Literal['<default>']:
        ...

default = ...
